y_raiso_cas_auth:
  server_login_url: '%env(CAS_LOGIN)%'
  server_validation_url: '%env(CAS_VALIDATE)%'
  server_logout_url: '%env(CAS_LOGOUT)%'
  server_force_redirect_https: '%env(bool:REDIRECT_HTTPS)%'
  xml_namespace: 'cas'
  options: []